import { VerticalBox, ScrollView } from "std-widgets.slint";

export component AppWindow inherits Window {
    no-frame: true;
    width: 600px;
    height: 400px;
    background: #192128;
    forward-focus: key-handler;
    callback close-app;
    in-out property <int> selected-index: 0;
    in-out property <int> row-count: 30;
    in-out property <brush> active-bg: #141617;
    in property <[[string]]> tableAlias;

    key-handler := FocusScope {
        key-pressed(event) => {
            if (event.text == "q") {
                root.close-app();
                accept;
            }
            if (event.text == "j" || event.text == "J") {
                if (root.selected-index < root.row-count - 1) {
                    root.selected-index += 1;
                }
                accept;
            }
            if (event.text == "k" || event.text == "K") {
                if (root.selected-index > 0) {
                    root.selected-index -= 1;
                }
                accept;
            }
            accept;
        }
    }

    Rectangle {
        width: 100%;
        height: 100%;
        border-width: 2px;
        border-radius: 8px;
        border-color: transparent;
        VerticalLayout {
            spacing: 6px;

            // Header
            HorizontalLayout {
                alignment: center;
                Rectangle {
                    background: #b6c2ea;
                    width: 80px;
                    height: 24px;
                    Text {
                        text: "Alias";
                        color: #282c2f;
                        font-family: "monospace";
                        font-size: 18px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }
            }

            scroll-view := ScrollView {
                vertical-scrollbar-policy: ScrollBarPolicy.as-needed;
                height: 100%;
                VerticalLayout {
                    width: 100%;
                    spacing: 8px;

                    for i in 30: Rectangle {
                        background: root.selected-index == i ? active-bg : transparent;
                        opacity: 0.5;
                        height: 30px;
                        border-radius: 1px;
                        HorizontalLayout {
                            padding-left: 18px;
                            padding-right: 18px;
                            alignment: stretch;
                            Text {
                                text: "hi";
                                color: white;
                                font-family: "monospace";
                                font-size: 18px;
                                vertical-alignment: center;
                                horizontal-stretch: 1;
                            }

                            Text {
                                text: "used to say hello";
                                color: #aab0c4;
                                font-family: "monospace";
                                font-size: 18px;
                                vertical-alignment: center;
                                horizontal-alignment: right;
                            }
                        }
                    }
                }
            }
        }
    }
}
