import { VerticalBox, ScrollView, Button } from "std-widgets.slint";
import { Theme } from "./theme.slint";

struct Alias {
   name: string,
	 meaning: string,
}
export component AppWindow inherits Window {
    no-frame: true;
    width: 600px;
    height: 400px;
    forward-focus: key-handler;
    background: Theme.BG;
    callback close-app;
    callback calculate-page;
    callback send-a-alias-name(string);
    out property <int> selected-index: 0;
    in property <int> row_count;
    out property <int> maxItemInPage: 9;
    out property <int> currentPage: 1;
    out property <int> max_row: 1;
    out property <brush> active-bg: #141617;
    in property <[Alias]> aliases_table;
    in property <int> page_count;

    key-handler := FocusScope {
        key-pressed(event) => {
            if (event.text == "q") {
                root.close-app();
                accept;
            }
            if (event.text == "j" || event.text == "J") {
                if (currentPage == page_count) {
                    root.max_row = Math.mod(root.aliases_table.length, root.maxItemInPage)
                } else {
                    root.max_row = root.maxItemInPage
                }
                if (root.selected-index < root.max_row - 1) {
                    root.selected-index += 1;
                }
                accept;
            }
            if (event.text == "h" || event.text == "H") {
                if (root.currentPage > 1) {
                    root.currentPage -= 1;
                }
                root.selected-index = 0;
                accept;
            }
            if (event.text == "l" || event.text == "L") {
                if (root.currentPage < root.page_count) {
                    root.currentPage += 1;
                }
                root.selected-index = 0;
                accept;
            }
            if (event.text == "k" || event.text == "K") {
                if (root.selected-index > 0) {
                    root.selected-index -= 1;
                }
                accept;
            }
            if (event.text == "\n") {
                root.send-a-alias-name(aliases_table[(root.currentPage - 1) * root.maxItemInPage + selected-index].name);
                accept;
            }
            accept;
        }
    }

    Rectangle {
        width: 100%;
        height: 100%;
        border-width: 2px;
        border-radius: 8px;
        border-color: transparent;
        VerticalLayout {
            spacing: 6px;

            // Header
            HorizontalLayout {
                alignment: center;
                Rectangle {
                    background: Theme.BG_HEADER;
                    width: 80px;
                    height: 24px;
                    Text {
                        text: "Alias";
                        color: Theme.TEXT_HEADER;
                        font-family: "monospace";
                        font-size: 18px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }
            }

            VerticalLayout {
                width: 100%;
                spacing: 8px;

                for i in maxItemInPage: Rectangle {
                    background: root.selected-index == i ? Theme.HOVER : transparent;
                    opacity: 0.5;
                    height: 30px;
                    border-radius: 1px;
                    HorizontalLayout {
                        padding-left: 18px;
                        padding-right: 18px;
                        alignment: stretch;
                        Text {
                            text: aliases_table[(root.currentPage - 1) * root.maxItemInPage + i].name;
                            color: root.selected-index == i ? Theme.HOVER_TEXT : Theme.TEXT;
                            font-family: "monospace";
                            font-size: 18px;
                            vertical-alignment: center;
                            horizontal-stretch: 1;
                        }

                        Text {
                            text: aliases_table[(root.currentPage - 1) * root.maxItemInPage + i].meaning;
                            color: root.selected-index == i ? Theme.HOVER_TEXT : Theme.TEXT;
                            font-family: "monospace";
                            font-size: 18px;
                            vertical-alignment: center;
                            horizontal-alignment: right;
                        }
                    }
                }
            }

            HorizontalLayout {
                alignment: center;
                spacing: 8px;
                padding-top: 8px;
                Rectangle {
                    background: Theme.BG_FOOTER;
                    width: 80px;
                    height: 24px;
                    Text {
                        text: root.currentPage + " of " + root.page_count;
                        color: Theme.TEXT_FOOTER;
                        font-family: "monospace";
                        font-size: 16px;
                        vertical-alignment: center;
                    }
                }
            }
        }
    }
}
