export global Theme {
//  ------------ dark --------------
    out property <color> BG: #1f2130;
    out property <color> TEXT: #bbc5ce;
    out property <color> HOVER: #2b3155;
    out property <color> HOVER_TEXT: #cdd1e4;
    out property <color> BG_HEADER: #b6bd88;
    out property <color> TEXT_HEADER: #1b1d23;
    out property <color> BG_FOOTER: #818595;
    out property <color> TEXT_FOOTER: #1c1c20;
}
